'use client'

import { STATUS_ATENDIMENTO, STATUS_ATENDIMENTO_LABEL } from "@/utils/types/status-atentimento-enum"

export const nomeStatusAtentimento = {
    [STATUS_ATENDIMENTO.ATENDIMENTO_INICIAL]: STATUS_ATENDIMENTO_LABEL.ATENDIMENTO_INICIAL,
    [STATUS_ATENDIMENTO.EM_NEGOCIACAO]: STATUS_ATENDIMENTO_LABEL.EM_NEGOCIACAO,
    [STATUS_ATENDIMENTO.PERDIDO]: STATUS_ATENDIMENTO_LABEL.PERDIDO,
    [STATUS_ATENDIMENTO.PRE_ATENDIMENTO]: STATUS_ATENDIMENTO_LABEL.PRE_ATENDIMENTO,
    [STATUS_ATENDIMENTO.RESGATE]: STATUS_ATENDIMENTO_LABEL.RESGATE,
    [STATUS_ATENDIMENTO.SUCESSO]: STATUS_ATENDIMENTO_LABEL.SUCESSO,
    [STATUS_ATENDIMENTO.VISITA]: STATUS_ATENDIMENTO_LABEL.VISITA,
    [STATUS_ATENDIMENTO.CHAT]: STATUS_ATENDIMENTO_LABEL.CHAT,
}