version: '3.8'

services:
  autopilot-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autopilot-frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
    restart: unless-stopped
