export const TIPO_EVENTO_LOG = {
  CRIACAO: 'Criação',
  MUDANCA_STATUS: 'Mudança de Situação',
  ATRIBUICAO_RESPONSAVEL: 'Atribuição de Responsável',
  REMOCAO_RESPONSAVEL: 'Remoção de Responsável',
  ADICAO_COMENTARIO: 'Adição de Comentário',
  AGENDAMENTO_VISITA: 'Agendamento de Visita',
  CONCLUSAO_VISITA: 'Conclusão de Visita',
  CRIACAO_TAREFA: 'Criação de Tarefa',
  CONCLUSAO_TAREFA: 'Conclusão de Tarefa',
  REMOCAO_TAREFA: 'Remoção de Tarefa',
  ALTERACAO_TIPO_ATENDIMENTO: 'Alteração de Tipo de Atendimento',
  ALTERACAO_DADOS_CLIENTE: 'Alteração de Dados do Cliente',
  ARQUIVAMENTO: 'Arquivamento',
  DESARQUIVAMENTO: 'Desarquivamento',
  ALTERACAO_TITULO: 'Alteração de Título',
  ALTERACAO_OBSERVACAO: 'Alteração de Observação',
  ALTERACAO_TEMPERATURA: 'Alteração de Temperatura',
  ADICAO_ANEXO: 'Adição de Anexo',
  REMOCAO_ANEXO: 'Remoção de Anexo',
  COMPARTILHAMENTO: 'Compartilhamento',
  SUSPENSAOCRIADA: 'Suspensão Criada',
  SUSPENSAOATUALIZADA: 'Suspensão Atualizada',
  SUSPENSAOREMOVIDA: 'Suspensão Removida',
  DISTRIBUICAOCONFIGURADA: 'Distribuição Configurada',
  ATENDIMENTOSREDISTRIBUIDOS: 'Atendimentos Redistribuídos',
  MONITORAMENTOEXECUTADO: 'Monitoramento Executado',
  ALTERACAONOMETAREFA: 'Alteração de Nome de Tarefa',
  ALTERACAOOBSERVACOESTAREFA: 'Alteração de Observações de Tarefa',
  ALTERACAORESPONSAVELTAREFA: 'Alteração de Responsável de Tarefa',
  ALTERACAOHORAINICIOTAREFA: 'Alteração de Hora de Início de Tarefa',
  ALTERACAOHORAFIMTAREFA: 'Alteração de Hora de Fim de Tarefa',
  ALTERACAODATATAREFA: 'Alteração de Data de Tarefa',
  CREATION: 'Criação',
  CHANGE_STATUS: 'Mudança de Situação',
  ASSIGNMENT_ASSIGNEE: 'Atribuição de Responsável',
  REMOVAL_ASSIGNEE: 'Remoção de Responsável',
  ADDITION_COMMENT: 'Adição de Comentário',
  SCHEDULING_VISIT: 'Agendamento de Visita',
  COMPLETION_VISIT: 'Conclusão de Visita',
  CREATION_TASK: 'Criação de Tarefa',
  COMPLETION_TASK: 'Conclusão de Tarefa',
  REMOVAL_TASK: 'Remoção de Tarefa',
  CHANGE_TYPE_DEAL: 'Alteração de Tipo de Atendimento',
  CHANGE_DATA_CUSTOMER: 'Alteração de Dados do Cliente',
  ARCHIVING: 'Arquivamento',
  UNARCHIVING: 'Desarquivamento',
  CHANGE_TITLE: 'Alteração de Título',
  CHANGE_NOTE: 'Alteração de Observação',
  CHANGE_TEMPERATURE: 'Alteração de Temperatura',
  ADDITION_ATTACHMENT: 'Adição de Anexo',
  REMOVAL_ATTACHMENT: 'Remoção de Anexo',
  SHARE: 'Compartilhamento',
  SUSPENSION_CREATED: 'Suspensão Criada',
  SUSPENSION_UPDATED: 'Suspensão Atualizada',
  SUSPENSION_REMOVED: 'Suspensão Removida',
  DISTRIBUTION_CONFIGURED: 'Distribuição Configurada',
  DEALS_REDISTRIBUTED: 'Atendimentos Redistribuídos',
  MONITORING_EXECUTED: 'Monitoramento Executado',
  CHANGE_NAME_TASK: 'Alteração de Nome de Tarefa',
  CHANGE_NOTES_TASK: 'Alteração de Observações de Tarefa',
  CHANGE_ASSIGNEE_TASK: 'Alteração de Responsável de Tarefa',
  CHANGE_HOUR_START_TASK: 'Alteração de Hora de Início de Tarefa',
  CHANGE_HOUR_END_TASK: 'Alteração de Hora de Fim de Tarefa',
  CHANGE_DATA_TASK: 'Alteração de Data de Tarefa',
  CONFIRMATION_VISIT: 'Confirmação de visita',
  REMOVAL_VISIT: 'Remoção de visita',
};
