export enum DealLossReason {
  FINANCIAL_CREDIT = 'financialCredit',
  PROPOSAL_VALUATION = 'proposalValuation',
  INVENTORY_PRODUCT = 'inventoryProduct',
  WITHOUT_RESULT = 'withoutResult',
  COMPETITION_OTHER_STORE = 'competitionOtherStore',
  INTEREST_INTENT = 'interestIntent',
  OTHER_REASONS = 'otherReasons',
}
export enum DealLossSubReason {
  // 1. Financeiro / Crédito
  FINANCING_NOT_APPROVED = 'financingNotApproved',
  SCORE_CREDIT_INSUFFICIENT = 'scoreCreditInsufficient',
  INCOMING_VERY_LOW = 'incomingVeryLow',
  VALUE_INSTALLMENT_INCOMPATIBLE_INCOME = 'valueInstallmentIncompatibleIncome',
  CUSTOMER_WITHOUT_CREDIT_AVAILABLE = 'customerWithoutCreditAvailable',
  CONDITION_FINANCING_NOT_ACCEPTED = 'conditionFinancingNotAccepted',
  CUSTOMER_WITHDREW_AFTER_REJECTION = 'customerWithdrewAfterRejection',
  BANK_REJECTED_PROPOSAL = 'bankRejectedProposal',
  CUSTOMER_NOT_WANTED_PROVIDE_DATA_CREDIT = 'customerNotWantedProvideDataCredit',
  // 2. Proposta / Avaliação
  CUSTOMER_NOT_LIKED_VALUATION = 'customerNotLikedValuation',
  PROPOSAL_INCOMPATIBLE_MARKET = 'proposalIncompatibleMarket',
  VALUATION_BELOW_EXPECTED = 'valuationBelowExpected',
  CUSTOMER_FOUND_PRICE_HIGH = 'customerFoundPriceHigh',
  REQUEST_DISCOUNT_BEYOND_ALLOWED = 'requestDiscountBeyondAllowed',
  STORE_NOT_ACCEPTED_VALUE_TRADEIN = 'storeNotAcceptedValueTradeIn',
  VALUE_PROPOSAL_BELOW_EXPECTED = 'valueProposalBelowExpected',
  DIFFERENCE_VALUES_NEGOTIATION = 'differenceValuesNegotiation',
  // 3. Estoque / Produto
  WITHOUT_VEHICLE_INTEREST_INVENTORY = 'withoutVehicleInterestInventory',
  VEHICLE_WAS_SOLD_BEFORE_NEGOTIATION = 'vehicleWasSoldBeforeNegotiation',
  VEHICLE_AWAITING_PREPARATION = 'vehicleAwaitingPreparation',
  VEHICLE_RESERVED_OTHER_CUSTOMER = 'vehicleReservedOtherCustomer',
  DOCUMENTATION_PENDING = 'documentationPending',
  VEHICLE_TRADEIN_NOT_INTERESTS = 'vehicleTradeInNotInterests',
  MODEL_DESIRED_NOT_SUPPORTED_STORE = 'modelDesiredNotSupportedStore',
  COLOR_VERSION_UNAVAILABLE = 'colorVersionUnavailable',
  // 4. Sem Retorno
  CUSTOMER_NOT_REPLIED = 'customerNotReplied',
  CUSTOMER_NOT_RETURNED_AFTER_PROPOSAL = 'customerNotReturnedAfterProposal',
  CUSTOMER_BLOCKED_CONTACT = 'customerBlockedContact',
  DATA_CONTACT_INCORRECT = 'dataContactIncorrect',
  PHONE_WHATSAPP_INVALID = 'phoneWhatsappInvalid',
  CUSTOMER_SAID_WOULDRETURN_NOT_RETURNED = 'customerSaidWouldReturnNotReturned',
  CUSTOMER_IGNORED_MESSAGES = 'customerIgnoredMessages',
  CUSTOMER_DISAPPEARED_AFTER_CONVERSATION_INITIAL = 'customerDisappearedAfterConversationInitial',
  // 5. Concorrência / Outra Loja
  CUSTOMER_NEGOTIATED_OTHER_STORE = 'customerNegotiatedOtherStore',
  CUSTOMER_ALREADY_PURCHASED_OTHER_VEHICLE = 'customerAlreadyPurchasedOtherVehicle',
  RECEIVED_PROPOSAL_BEST_COMPETITION = 'receivedProposalBestCompetition',
  CHOSE_OTHER_MODEL_BRAND = 'choseOtherModelBrand',
  PREFERRED_DEALERSHIP = 'preferredDealership',
  PURCHASED_PRIVATE = 'purchasedPrivate',
  CLOSED_OTHER_CITY = 'closedOtherCity',
  // 6. Interesse / Intenção
  CUSTOMER_WITHDREW_NEGOTIATION = 'customerWithdrewNegotiation',
  CUSTOMER_POSTPONED_BUY = 'customerPostponedBuy',
  CUSTOMER_THINKING = 'customerThinking',
  CUSTOMER_ONLY_RESEARCHING = 'customerOnlyResearching',
  WILL_WAIT_NEW_MODEL = 'willWaitNewModel',
  WILL_BUY_NEXT_MONTH = 'willBuyNextMonth',
  WILL_KEEP_CAR_CURRENT = 'willKeepCarCurrent',
  CHANGED_IDEA_AFTER_CONVERSATION = 'changedIdeaAfterConversation',
  // 7. Outros Motivos
  CUSTOMER_NOT_CAME_STORE = 'customerNotCameStore',
  LIVES_FAR_UNFEASIBLE_TRAVEL = 'livesFarUnfeasibleTravel',
  BECAME_SICK_UNEXPECTED_PERSONAL = 'becameSickImprevistosPersonal',
  DEAL_DUPLICATE = 'dealDuplicate',
  CUSTOMER_SERVED_OTHER_SALESPERSON = 'customerServedOtherSalesperson',
  CUSTOMER_PORTFOLIO_RELATIONSHIP_DIRECT = 'customerPortfolioRelationshipDirect',
  TIMING_OUTSIDE_MOMENT_BUY = 'timingOutsideMomentBuy',
  REQUESTED_PAUSE_TEMPORARY = 'requestedPauseTemporary',
  OTHER_REASON = 'otherReason',
}
export const SUBMOTIVOS_POR_MOTIVO: {
  [key in DealLossReason]: DealLossSubReason[];
} = {
  // Financeiro / Crédito
  [DealLossReason.FINANCIAL_CREDIT]: [
    DealLossSubReason.FINANCING_NOT_APPROVED,
    DealLossSubReason.SCORE_CREDIT_INSUFFICIENT,
    DealLossSubReason.INCOMING_VERY_LOW,
    DealLossSubReason.VALUE_INSTALLMENT_INCOMPATIBLE_INCOME,
    DealLossSubReason.CUSTOMER_WITHOUT_CREDIT_AVAILABLE,
    DealLossSubReason.CONDITION_FINANCING_NOT_ACCEPTED,
    DealLossSubReason.CUSTOMER_WITHDREW_AFTER_REJECTION,
    DealLossSubReason.BANK_REJECTED_PROPOSAL,
    DealLossSubReason.CUSTOMER_NOT_WANTED_PROVIDE_DATA_CREDIT,
  ],
  // Proposta / Avaliação
  [DealLossReason.PROPOSAL_VALUATION]: [
    DealLossSubReason.CUSTOMER_NOT_LIKED_VALUATION,
    DealLossSubReason.PROPOSAL_INCOMPATIBLE_MARKET,
    DealLossSubReason.VALUATION_BELOW_EXPECTED,
    DealLossSubReason.CUSTOMER_FOUND_PRICE_HIGH,
    DealLossSubReason.REQUEST_DISCOUNT_BEYOND_ALLOWED,
    DealLossSubReason.STORE_NOT_ACCEPTED_VALUE_TRADEIN,
    DealLossSubReason.VALUE_PROPOSAL_BELOW_EXPECTED,
    DealLossSubReason.DIFFERENCE_VALUES_NEGOTIATION,
  ],
  // Estoque / Produto
  [DealLossReason.INVENTORY_PRODUCT]: [
    DealLossSubReason.WITHOUT_VEHICLE_INTEREST_INVENTORY,
    DealLossSubReason.VEHICLE_WAS_SOLD_BEFORE_NEGOTIATION,
    DealLossSubReason.VEHICLE_AWAITING_PREPARATION,
    DealLossSubReason.VEHICLE_RESERVED_OTHER_CUSTOMER,
    DealLossSubReason.DOCUMENTATION_PENDING,
    DealLossSubReason.VEHICLE_TRADEIN_NOT_INTERESTS,
    DealLossSubReason.MODEL_DESIRED_NOT_SUPPORTED_STORE,
    DealLossSubReason.COLOR_VERSION_UNAVAILABLE,
  ],
  // Sem Retorno
  [DealLossReason.WITHOUT_RESULT]: [
    DealLossSubReason.CUSTOMER_NOT_REPLIED,
    DealLossSubReason.CUSTOMER_NOT_RETURNED_AFTER_PROPOSAL,
    DealLossSubReason.CUSTOMER_BLOCKED_CONTACT,
    DealLossSubReason.DATA_CONTACT_INCORRECT,
    DealLossSubReason.PHONE_WHATSAPP_INVALID,
    DealLossSubReason.CUSTOMER_SAID_WOULDRETURN_NOT_RETURNED,
    DealLossSubReason.CUSTOMER_IGNORED_MESSAGES,
    DealLossSubReason.CUSTOMER_DISAPPEARED_AFTER_CONVERSATION_INITIAL,
  ],
  // Concorrência / Outra Loja
  [DealLossReason.COMPETITION_OTHER_STORE]: [
    DealLossSubReason.CUSTOMER_NEGOTIATED_OTHER_STORE,
    DealLossSubReason.CUSTOMER_ALREADY_PURCHASED_OTHER_VEHICLE,
    DealLossSubReason.RECEIVED_PROPOSAL_BEST_COMPETITION,
    DealLossSubReason.CHOSE_OTHER_MODEL_BRAND,
    DealLossSubReason.PREFERRED_DEALERSHIP,
    DealLossSubReason.PURCHASED_PRIVATE,
    DealLossSubReason.CLOSED_OTHER_CITY,
  ],
  // Interesse / Intenção
  [DealLossReason.INTEREST_INTENT]: [
    DealLossSubReason.CUSTOMER_WITHDREW_NEGOTIATION,
    DealLossSubReason.CUSTOMER_POSTPONED_BUY,
    DealLossSubReason.CUSTOMER_THINKING,
    DealLossSubReason.CUSTOMER_ONLY_RESEARCHING,
    DealLossSubReason.WILL_WAIT_NEW_MODEL,
    DealLossSubReason.WILL_BUY_NEXT_MONTH,
    DealLossSubReason.WILL_KEEP_CAR_CURRENT,
    DealLossSubReason.CHANGED_IDEA_AFTER_CONVERSATION,
  ],
  // Outros Motivos
  [DealLossReason.OTHER_REASONS]: [
    DealLossSubReason.CUSTOMER_NOT_CAME_STORE,
    DealLossSubReason.LIVES_FAR_UNFEASIBLE_TRAVEL,
    DealLossSubReason.BECAME_SICK_UNEXPECTED_PERSONAL,
    DealLossSubReason.DEAL_DUPLICATE,
    DealLossSubReason.CUSTOMER_SERVED_OTHER_SALESPERSON,
    DealLossSubReason.CUSTOMER_PORTFOLIO_RELATIONSHIP_DIRECT,
    DealLossSubReason.TIMING_OUTSIDE_MOMENT_BUY,
    DealLossSubReason.REQUESTED_PAUSE_TEMPORARY,
    DealLossSubReason.OTHER_REASON,
  ],
};
