export enum StorePermission {
  STORE_VIEW_DASHBOARD = 'storeViewDashboard',
  STORE_VIEW_DEALS = 'storeViewDeals',
  STORE_EDIT_DELETE_DEAL = 'storeEditDeleteDeal',
  STORE_LINK_DEAL_USER = 'storeLinkDealUser',
  STORE_TRANSFER_DEAL = 'storeTransferDeal',
  STORE_VIEW_CHAT = 'storeViewChat',
  STORE_REPLY_CHAT = 'storeReplyChat',
  STORE_REGISTER_EDIT_CUSTOMERS = 'storeRegisterEditCustomers',
  STORE_SEARCH_CUSTOMERS = 'storeSearchCustomers',
  STORE_MANAGE_USERS = 'storeManageUsers',
  STORE_MANAGE_ROLES = 'storeManageRoles',
  STORE_CONFIGURE_INTEGRATIONS = 'storeConfigureIntegrations',
  STORE_EDIT_DATA_OF_STORE = 'storeEditDataOfStore',
  STORE_MANAGE_SUSPENSIONS = 'storeManageSuspensions',
  STORE_VIEW_ALL_DEALS = 'storeViewAllDeals',
  STORE_CREATE_DEAL_MANUAL = 'storeCreateDealManual',
  STORE_REASSIGN_DEALS = 'storeReassignDeals',
  STORE_MANAGE_TEAM = 'storeManageTeam',
  STORE_VIEW_DEALS_OWN = 'storeViewDealsOwn',
  STORE_CREATE_DEAL_OWN = 'storeCreateDealOwn',
  STORE_MANAGE_TASKS_OWN = 'storeManageTasksOwn',
  STORE_PRE_SALESPERSON_FINALIZE_DEAL = 'storePreSalespersonFinalizeDeal',
  STORE_VIEW_MESSAGES_TEMPLATE = 'storeViewMessagesTemplate',
  STORE_CREATE_MESSAGE_TEMPLATE = 'storeCreateMessageTemplate',
  STORE_EDIT_MESSAGE_TEMPLATE = 'storeEditMessageTemplate',
  STORE_DELETE_MESSAGE_TEMPLATE = 'storeDeleteMessageTemplate',
}
export enum AdminPermission {
  AUTOPILOT_VIEW_DASHBOARD = 'autopilotViewDashboard',
  AUTOPILOT_REPLY_TICKETS = 'autopilotReplyTickets',
  AUTOPILOT_VIEW_TICKETS = 'autopilotViewTickets',
  AUTOPILOT_UPDATE_PANEL_RESELLER = 'autopilotUpdatePanelReseller',
  AUTOPILOT_UPDATE_PERMISSIONS = 'autopilotUpdatePermissions',
  AUTOPILOT_CREATE_USER_ADMIN = 'autopilotCreateUserAdmin',
  AUTOPILOT_VIEW_USERS_ADMIN = 'autopilotViewUsersAdmin',
}
export const StorePermissionLabels: Record<StorePermission, string> = {
  [StorePermission.STORE_VIEW_DASHBOARD]: 'Visualizar Painel',
  [StorePermission.STORE_VIEW_DEALS]: 'Visualizar Atendimentos',
  [StorePermission.STORE_EDIT_DELETE_DEAL]: 'Editar/Excluir Atendimento',
  [StorePermission.STORE_LINK_DEAL_USER]: 'Vincular Atendimento a Usuário',
  [StorePermission.STORE_TRANSFER_DEAL]: 'Transferir Atendimento',
  [StorePermission.STORE_VIEW_CHAT]: 'Visualizar Conversa',
  [StorePermission.STORE_REPLY_CHAT]: 'Responder Conversa',
  [StorePermission.STORE_REGISTER_EDIT_CUSTOMERS]: 'Cadastrar/Editar Clientes',
  [StorePermission.STORE_SEARCH_CUSTOMERS]: 'Pesquisar Clientes',
  [StorePermission.STORE_MANAGE_USERS]: 'Gerenciar Usuários',
  [StorePermission.STORE_MANAGE_ROLES]: 'Gerenciar Cargos',
  [StorePermission.STORE_CONFIGURE_INTEGRATIONS]: 'Configurar Integrações',
  [StorePermission.STORE_EDIT_DATA_OF_STORE]: 'Editar Dados da Loja',
  [StorePermission.STORE_MANAGE_SUSPENSIONS]: 'Gerenciar Suspensões de Atendimento',
  [StorePermission.STORE_VIEW_ALL_DEALS]: 'Visualizar Todos os Atendimentos',
  [StorePermission.STORE_CREATE_DEAL_MANUAL]: 'Criar Atendimento Manual',
  [StorePermission.STORE_REASSIGN_DEALS]: 'Reatribuir Atendimentos',
  [StorePermission.STORE_MANAGE_TEAM]: 'Gerenciar Equipe',
  [StorePermission.STORE_VIEW_DEALS_OWN]: 'Visualizar Atendimentos Próprios',
  [StorePermission.STORE_CREATE_DEAL_OWN]: 'Criar Atendimento Próprio',
  [StorePermission.STORE_MANAGE_TASKS_OWN]: 'Gerenciar Tarefas Próprias',
  [StorePermission.STORE_PRE_SALESPERSON_FINALIZE_DEAL]: 'Pré-vendedor Finalizar Atendimento',
  [StorePermission.STORE_VIEW_MESSAGES_TEMPLATE]: 'Visualizar Mensagens Padrão',
  [StorePermission.STORE_CREATE_MESSAGE_TEMPLATE]: 'Criar Mensagem Padrão',
  [StorePermission.STORE_EDIT_MESSAGE_TEMPLATE]: 'Editar Mensagem Padrão',
  [StorePermission.STORE_DELETE_MESSAGE_TEMPLATE]: 'Deletar Mensagem Padrão',
};
export const AllPermissions = { ...StorePermissionLabels, ...AdminPermission };
