export const TIPO_EVENTO_LOG = {
  CRIACAO : 'Criação',
  MUDANCA_STATUS : 'Mudança de Status',
  ATRIBUICAO_RESPONSAVEL : 'Atribuição de Responsável',
  REMOCAO_RESPONSAVEL : 'Remoção de Responsável',
  ADICAO_COMENTARIO : 'Adição de Comentário',
  AGENDAMENTO_VISITA : 'Agendamento de Visita',
  CONCLUSAO_VISITA : 'Conclusão de Visita',
  CRIACAO_TAREFA : 'Criação de Tarefa',
  CONCLUSAO_TAREFA : 'Conclusão de Tarefa',
  REMOCAO_TAREFA : 'Remoção de Tarefa',
  ALTERACAO_TIPO_ATENDIMENTO : 'Alteração de Tipo de Atendimento',
  ALTERACAO_DADOS_CLIENTE : 'Alteração de Dados do Cliente',
  ARQUIVAMENTO : 'Arquivamento',
  DESARQUIVAMENTO : 'Desarquivamento',
  ALTERACAO_TITULO : 'Alteração de Título',
  ALTERACAO_OBSERVACAO : 'Alteração de Observação',
  ALTERACAO_TEMPERATURA : 'Alteração de Temperatura',
  ADICAO_ANEXO : 'Adição de Anexo',
  REMOCAO_ANEXO : 'Remoção de Anexo',
  COMPARTILHAMENTO : 'Compartilhamento',
  SUSPENSAOCRIADA : 'Suspensão Criada',
  SUSPENSAOATUALIZADA : 'Suspensão Atualizada',
  SUSPENSAOREMOVIDA : 'Suspensão Removida',
  DISTRIBUICAOCONFIGURADA : 'Distribuição Configurada',
  ATENDIMENTOSREDISTRIBUIDOS : 'Atendimentos Redistribuídos',
  MONITORAMENTOEXECUTADO : 'Monitoramento Executado',
  ALTERACAONOMETAREFA : 'Alteração de Nome de Tarefa',
  ALTERACAOOBSERVACOESTAREFA : 'Alteração de Observações de Tarefa',
  ALTERACAORESPONSAVELTAREFA : 'Alteração de Responsável de Tarefa',
  ALTERACAOHORAINICIOTAREFA : 'Alteração de Hora de Início de Tarefa',
  ALTERACAOHORAFIMTAREFA : 'Alteração de Hora de Fim de Tarefa',
  ALTERACAODATATAREFA : 'Alteração de Data de Tarefa',
}
