export enum MOTIVOS_PERDA_ATENDIMENTO {
  FINANCEIRO_CREDITO = 'financeiroCredito',
  PROPOSTA_AVALIACAO = 'propostaAvaliacao',
  ESTOQUE_PRODUTO = 'estoqueProduto',
  SEM_RETORNO = 'semRetorno',
  CONCORRENCIA_OUTRA_LOJA = 'concorrenciaOutraLoja',
  INTERESSE_INTENCAO = 'interesseIntencao',
  OUTROS_MOTIVOS = 'outrosMotivos',
}

export enum SUB_MOTIVOS_PERDA_ATENDIMENTO {
  // 1. Financeiro / Crédito
  FINANCIAMENTO_NAO_APROVADO = 'financiamentoNaoAprovado',
  SCORE_CREDITO_INSUFICIENTE = 'scoreCreditoInsuficiente',
  ENTRADA_MUITO_BAIXA = 'entradaMuitoBaixa',
  VALOR_PARCELA_INCOMPATIVEL_RENDA = 'valorParcelaIncompativelRenda',
  CLIENTE_SEM_CREDITO_DISPONIVEL = 'clienteSemCreditoDisponivel',
  CONDICAO_FINANCIAMENTO_NAO_ACEITA = 'condicaoFinanciamentoNaoAceita',
  CLIENTE_DESISTIU_APOS_REPROVACAO = 'clienteDesistiuAposReprovacao',
  BANCO_RECUSOU_PROPOSTA = 'bancoRecusouProposta',
  CLIENTE_NAO_QUIS_INFORMAR_DADOS_CREDITO = 'clienteNaoQuisInformarDadosCredito',

  // 2. Proposta / Avaliação
  CLIENTE_NAO_GOSTOU_AVALIACAO = 'clienteNaoGostouAvaliacao',
  PROPOSTA_INCOMPATIVEL_MERCADO = 'propostaIncompativelMercado',
  AVALIACAO_ABAIXO_ESPERADO = 'avaliacaoAbaixoEsperado',
  CLIENTE_ACHOU_PRECO_ALTO = 'clienteAchouPrecoAlto',
  PEDIDO_DESCONTO_ALEM_PERMITIDO = 'pedidoDescontoAlemPermitido',
  LOJA_NAO_ACEITOU_VALOR_TROCA = 'lojaNaoAceitouValorTroca',
  VALOR_PROPOSTA_ABAIXO_ESPERADO = 'valorPropostaAbaixoEsperado',
  DIVERGENCIA_VALORES_NEGOCIACAO = 'divergenciaValoresNegociacao',

  // 3. Estoque / Produto
  SEM_VEICULO_INTERESSE_ESTOQUE = 'semVeiculoInteresseEstoque',
  VEICULO_FOI_VENDIDO_ANTES_NEGOCIACAO = 'veiculoFoiVendidoAntesNegociacao',
  VEICULO_AGUARDANDO_PREPARACAO = 'veiculoAguardandoPreparacao',
  VEICULO_RESERVADO_OUTRO_CLIENTE = 'veiculoReservadoOutroCliente',
  DOCUMENTACAO_PENDENTE = 'documentacaoPendente',
  VEICULO_TROCA_NAO_INTERESSA = 'veiculoTrocaNaoInteressa',
  MODELO_DESEJADO_NAO_TRABALHADO_LOJA = 'modeloDesejadoNaoTrabalhadoLoja',
  COR_VERSAO_INDISPONIVEL = 'corVersaoIndisponivel',

  // 4. Sem Retorno
  CLIENTE_NAO_RESPONDEU = 'clienteNaoRespondeu',
  CLIENTE_NAO_RETORNOU_APOS_PROPOSTA = 'clienteNaoRetornouAposProposta',
  CLIENTE_BLOQUEOU_CONTATO = 'clienteBloqueouContato',
  DADOS_CONTATO_INCORRETOS = 'dadosContatoIncorretos',
  TELEFONE_WHATSAPP_INVALIDO = 'telefoneWhatsappInvalido',
  CLIENTE_DISSE_RETORNARIA_NAO_RETORNOU = 'clienteDisseRetornariaNaoRetornou',
  CLIENTE_IGNOROU_MENSAGENS = 'clienteIgnorouMensagens',
  CLIENTE_SUMIU_APOS_CONVERSA_INICIAL = 'clienteSumiuAposConversaInicial',

  // 5. Concorrência / Outra Loja
  CLIENTE_NEGOCIOU_OUTRA_LOJA = 'clienteNegociouOutraLoja',
  CLIENTE_JA_COMPROU_OUTRO_VEICULO = 'clienteJaComprouOutroVeiculo',
  RECEBEU_PROPOSTA_MELHOR_CONCORRENCIA = 'recebeuPropostaMelhorConcorrencia',
  ESCOLHEU_OUTRO_MODELO_MARCA = 'escolheuOutroModeloMarca',
  PREFERIU_CONCESSIONARIA = 'preferiuConcessionaria',
  COMPROU_PARTICULAR = 'comprouParticular',
  FECHOU_OUTRA_CIDADE = 'fechouOutraCidade',

  // 6. Interesse / Intenção
  CLIENTE_DESISTIU_NEGOCIACAO = 'clienteDesistiuNegociacao',
  CLIENTE_ADIOU_COMPRA = 'clienteAdiouCompra',
  CLIENTE_PENSANDO = 'clientePensando',
  CLIENTE_APENAS_PESQUISANDO = 'clienteApenasPesquisando',
  VAI_ESPERAR_NOVO_MODELO = 'vaiEsperarNovoModelo',
  VAI_COMPRAR_PROXIMO_MES = 'vaiComprarProximoMes',
  VAI_MANTER_CARRO_ATUAL = 'vaiManterCarroAtual',
  MUDOU_IDEIA_APOS_CONVERSA = 'mudouIdeiaAposConversa',

  // 7. Outros Motivos
  CLIENTE_NAO_VEIO_LOJA = 'clienteNaoVeioLoja',
  MORA_LONGE_INVIAVEL_DESLOCAMENTO = 'moraLongeInviavelDeslocamento',
  FICOU_DOENTE_IMPREVISTO_PESSOAL = 'ficouDoenteImprevistosPessoal',
  ATENDIMENTO_DUPLICADO = 'atendimentoDuplicado',
  CLIENTE_ATENDIDO_OUTRO_VENDEDOR = 'clienteAtendidoOutroVendedor',
  CLIENTE_CARTEIRA_RELACIONAMENTO_DIRETO = 'clienteCarteiraRelacionamentoDireto',
  TIMING_FORA_MOMENTO_COMPRA = 'timingForaMomentoCompra',
  SOLICITOU_PAUSA_TEMPORARIA = 'solicitouPausaTemporaria',
  OUTRO_MOTIVO = 'outroMotivo',
}

export const SUBMOTIVOS_POR_MOTIVO: { [key in MOTIVOS_PERDA_ATENDIMENTO]: SUB_MOTIVOS_PERDA_ATENDIMENTO[] } = {
  // Financeiro / Crédito
  [MOTIVOS_PERDA_ATENDIMENTO.FINANCEIRO_CREDITO]: [
    SUB_MOTIVOS_PERDA_ATENDIMENTO.FINANCIAMENTO_NAO_APROVADO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.SCORE_CREDITO_INSUFICIENTE,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.ENTRADA_MUITO_BAIXA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.VALOR_PARCELA_INCOMPATIVEL_RENDA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_SEM_CREDITO_DISPONIVEL,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CONDICAO_FINANCIAMENTO_NAO_ACEITA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_DESISTIU_APOS_REPROVACAO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.BANCO_RECUSOU_PROPOSTA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_NAO_QUIS_INFORMAR_DADOS_CREDITO,
  ],

  // Proposta / Avaliação
  [MOTIVOS_PERDA_ATENDIMENTO.PROPOSTA_AVALIACAO]: [
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_NAO_GOSTOU_AVALIACAO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.PROPOSTA_INCOMPATIVEL_MERCADO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.AVALIACAO_ABAIXO_ESPERADO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_ACHOU_PRECO_ALTO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.PEDIDO_DESCONTO_ALEM_PERMITIDO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.LOJA_NAO_ACEITOU_VALOR_TROCA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.VALOR_PROPOSTA_ABAIXO_ESPERADO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.DIVERGENCIA_VALORES_NEGOCIACAO,
  ],

  // Estoque / Produto
  [MOTIVOS_PERDA_ATENDIMENTO.ESTOQUE_PRODUTO]: [
    SUB_MOTIVOS_PERDA_ATENDIMENTO.SEM_VEICULO_INTERESSE_ESTOQUE,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.VEICULO_FOI_VENDIDO_ANTES_NEGOCIACAO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.VEICULO_AGUARDANDO_PREPARACAO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.VEICULO_RESERVADO_OUTRO_CLIENTE,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.DOCUMENTACAO_PENDENTE,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.VEICULO_TROCA_NAO_INTERESSA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.MODELO_DESEJADO_NAO_TRABALHADO_LOJA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.COR_VERSAO_INDISPONIVEL,
  ],

  // Sem Retorno
  [MOTIVOS_PERDA_ATENDIMENTO.SEM_RETORNO]: [
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_NAO_RESPONDEU,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_NAO_RETORNOU_APOS_PROPOSTA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_BLOQUEOU_CONTATO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.DADOS_CONTATO_INCORRETOS,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.TELEFONE_WHATSAPP_INVALIDO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_DISSE_RETORNARIA_NAO_RETORNOU,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_IGNOROU_MENSAGENS,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_SUMIU_APOS_CONVERSA_INICIAL,
  ],

  // Concorrência / Outra Loja
  [MOTIVOS_PERDA_ATENDIMENTO.CONCORRENCIA_OUTRA_LOJA]: [
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_NEGOCIOU_OUTRA_LOJA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_JA_COMPROU_OUTRO_VEICULO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.RECEBEU_PROPOSTA_MELHOR_CONCORRENCIA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.ESCOLHEU_OUTRO_MODELO_MARCA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.PREFERIU_CONCESSIONARIA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.COMPROU_PARTICULAR,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.FECHOU_OUTRA_CIDADE,
  ],

  // Interesse / Intenção
  [MOTIVOS_PERDA_ATENDIMENTO.INTERESSE_INTENCAO]: [
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_DESISTIU_NEGOCIACAO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_ADIOU_COMPRA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_PENSANDO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_APENAS_PESQUISANDO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.VAI_ESPERAR_NOVO_MODELO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.VAI_COMPRAR_PROXIMO_MES,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.VAI_MANTER_CARRO_ATUAL,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.MUDOU_IDEIA_APOS_CONVERSA,
  ],

  // Outros Motivos
  [MOTIVOS_PERDA_ATENDIMENTO.OUTROS_MOTIVOS]: [
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_NAO_VEIO_LOJA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.MORA_LONGE_INVIAVEL_DESLOCAMENTO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.FICOU_DOENTE_IMPREVISTO_PESSOAL,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.ATENDIMENTO_DUPLICADO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_ATENDIDO_OUTRO_VENDEDOR,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.CLIENTE_CARTEIRA_RELACIONAMENTO_DIRETO,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.TIMING_FORA_MOMENTO_COMPRA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.SOLICITOU_PAUSA_TEMPORARIA,
    SUB_MOTIVOS_PERDA_ATENDIMENTO.OUTRO_MOTIVO,
  ],
};
